### ISSUE TITLE
Module doesnt work

### ISSUE THREAD

**Issue by laasker** [azerothcore/mod-morphsummon#19]
The NPC ingame doesnt give you options to morph your pet. If you doesnt have a pet, the npc will say:
''I am sorry, but you don''t have a summoned creature that I can polymorph'', 

but if you have a pet like voidwalker/felhunter, the following appears: 
![image](https://user-images.githubusercontent.com/79991768/180693036-5465c58d-5d10-41a2-9d6a-0f38d2237821.png)

**Comment by Helias** [comment]
did you import the sql file?

**Comment by laasker** [comment]
> did you import the sql file?

yes i did

**Comment by damiansp21** [comment]
any new on this?¿ the problem is still present.

**Comment by pangolp** [comment]
If the tests are successful and there are no bugs, please test the changes made in this pull request https://github.com/azerothcore/mod-morphsummon/pull/21. Thank you.

**Comment by pangolp** [comment]
In the end, that pull request does not solve the problem, however, in another pull request, we will check what is wrong with the module.

**Comment by laasker** [comment]
i found the problem, it's in
"// Mage Pet (minion)
        if (Minion *minion = player->GetFirstMinion())
        {
            if (minion->GetUInt32Value(UNIT_CREATED_BY_SPELL) == SUMMON_WATER_ELEMENTAL)
            {
                if (!mage_water_elemental.empty())
                {
                    AddGossipItemFor(player, MORPH_GOSSIP_MENU_HELLO, MORPH_GOSSIP_OPTION_POLYMORPH, GOSSIP_SENDER_MAIN, MORPH_PAGE_START_MAGE_WATER_ELEMENTAL);
                }
            }
        }
        else"
        
        i changed to 
        " // Mage Pet (minion)
        if (player->getClass() == CLASS_MAGE)
        {
            if (Minion* minion = player->GetFirstMinion())
            {
                if (minion->GetUInt32Value(UNIT_CREATED_BY_SPELL) == SUMMON_WATER_ELEMENTAL)
                {
                    if (!mage_water_elemental.empty())
                    {
                        AddGossipItemFor(player, MORPH_GOSSIP_MENU_HELLO, MORPH_GOSSIP_OPTION_POLYMORPH, GOSSIP_SENDER_MAIN, MORPH_PAGE_START_MAGE_WATER_ELEMENTAL);
                    }
                }
            }
        }
        else"
        
        and now it works
